# Generated by Django 5.1.4 on 2024-12-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default=11, max_length=50, verbose_name='username'),
            preserve_default=False,
        ),
    ]
