# Generated by Django 5.1.4 on 2024-12-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cartmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
